### ISSUE TITLE
Umm...unexpected negative random numbers

### ISSUE THREAD

**Issue by ujwal-setlur** [transitive-bullshit/random#28]
Here is my code:

index.ts:
```ts
import random from 'random';

const min = 0;
const max = 14206147658

for (let i = 0; i < 100; i = i+1) {
  const randomInt = random.int(min, max);
  console.log(`${i}: random: ${randomInt}`);
}
```

Here is a sample of my result:
```
0: random: 727406658
1: random: -579739191
2: random: -42082040
3: random: -915337893
4: random: 1667450201
5: random: 120576257
6: random: -839908019
7: random: 626427272
8: random: 345808248
9: random: 1928860574
10: random: 241466404
...
```

Why am I getting negative results?

**Comment by transitive-bullshit** [comment]
@ujwal-setlur thanks so much for the bug report and detailed repro scenario.

We were using a trick where in JS if you take a float and OR it with 0, you coerce it to an integer, but this apparently doesn't work with larger numbers, so the fix was to just switch to `Math.floor` instead.

Fix released as `v3.0.6`. https://github.com/transitive-bullshit/random/commit/8df781af1d70ac432b986487deed6415c4c22cba

I also added a test case to make sure we're covering the use case for larger numbers.

Thanks again 🙏

**Comment by ujwal-setlur** [comment]
Super quick response! I’ll test this. Thanks!

**Comment by ujwal-setlur** [comment]
Confirmed fixed!
